import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import GameCard from '../components/cards/gameCard'

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className='flex'>
      <div className='mx-auto'>
        <div style={{width:'250px', height:'250px'}}>
          <GameCard title={''} gameImageUrl={'https://cdn.discordapp.com/attachments/1022347629344063581/1022347699422503003/d681acd50b03a07815103f41543abba8.jpeg'} tags={['123']}></GameCard>
        </div>
      </div>
    </main>


    <footer>
    </footer>
  </div>
)

export default Home